FROM node:20-alpine

# Set the working directory to /app inside the container
WORKDIR /app
COPY package*.json ./

# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci

# Copy app files
COPY . .

# Run app on localhost:3000
EXPOSE 3000
CMD ["npm", "run", "start"]
